### ISSUE TITLE
Reordering of packets for PacketConn

### ISSUE THREAD

**Issue by foxcpp** [cevatbarisyilmaz/lossy#1]
Since UDP does not promise anything about ordered delivery, it would be nice to be able to test protocols to make sure they don't rely on packets order.

Though, I am not sure how this would work with bandwidth limitations and latency.

**Comment by cevatbarisyilmaz** [comment]
It's already possible via latency values. For example, if you send two packets with 10ms interval while minLatency is 100ms and maxLatency is1000ms, first packet may get affected from latency by 250ms, and second one by 150ms, which will cause an unordered delivery since second packet will be delivered 90ms earlier than the first one.

Greater differences between minLatency and maxLatency will cause more unordered packets.

**Comment by foxcpp** [comment]
Ah, got it, thanks.
